const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
const fs=require('node:fs');
const output=process.env.GZL_TEST_OUTPUT || path.join(__dirname,'test-results');
fs.mkdirSync(output,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:1280,height:800}});
 const errors=[]; const external=[];
 page.on('pageerror',e=>errors.push(e.message));
 page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:'))external.push(r.url())});
 await page.goto('http://127.0.0.1:8888/');
 await page.waitForFunction(()=>character3DReady);
 assert.equal(await page.evaluate(()=>state),'start');
 await page.mouse.click(250,300);
 assert.equal(await page.evaluate(()=>state),'ready');
 await page.locator('#companion-toggle').click();
 await page.locator('#companion-input').fill('测试消息');
 await page.mouse.click(250,300);
 assert.equal(await page.evaluate(()=>state),'ready');
 await page.waitForTimeout(1000);
 await page.screenshot({path:path.join(output,'desktop-preview.png')});
 await page.route('http://127.0.0.1:8765/api/chat',async route=>{
  const data=route.request().postDataJSON(); assert.equal(data.history.length,0);
  await new Promise(r=>setTimeout(r,300));
  await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({reply:'我是 AI 游戏角色，这是虚构测试回复。',display_name:'目标角色'})});
 });
 await page.locator('#companion-input').press('Enter');
 await page.waitForFunction(()=>companionBusy);
 assert.equal(await page.locator('#companion-send').isDisabled(),true);
 await page.waitForFunction(()=>!companionBusy);
 assert.equal(await page.evaluate(()=>companionHistory.length),2);
 assert.equal(await page.locator('#companion-name').textContent(),'目标角色');
 await page.locator('#companion-input').press('Escape');
 assert.equal(await page.locator('#companion-panel').isVisible(),false);
 // Real press/release with state-based charge timing, then natural landing.
 await page.mouse.move(250,300); await page.mouse.down();
 await page.waitForFunction(()=>chargeT >= Math.max(0,(plats[indexOfChar()+1].dist-2)/3));
 await page.mouse.up();
 assert.equal(await page.evaluate(()=>ch.jumping),true);
 await page.waitForFunction(()=>ch.jumpT>.2 && ch.jumpT<.8);
 assert.equal(await page.evaluate(()=>Math.abs(flipPivot3D.quaternion.w)<.9999),true);
 assert.equal(await page.evaluate(()=>jumpCameraY>=0),true);
 const boundary=await page.evaluate(()=>({top:H*.42+isoY(ch.col,ch.row)-camIsoY()-TILE_Z-ch.jumpZ-CHARACTER_MODEL_HEIGHT*WORLD_SCALE+jumpCameraY,safe:Math.max(20,24*SCALE)}));
 assert.ok(boundary.top>=boundary.safe-15);
 await page.waitForFunction(()=>state==='ready');
 assert.ok(await page.evaluate(()=>score)>0);
 // Force a deliberately missed target in a test-only state; exercise actual input/restart.
 await page.evaluate(()=>plats[indexOfChar()+1].dist=12);
 await page.mouse.down(); await page.waitForTimeout(30); await page.mouse.up();
 await page.waitForFunction(()=>state==='dead' && deadFrames>55);
 await page.mouse.click(250,300);
 assert.equal(await page.evaluate(()=>state),'start');
 await page.reload();
 assert.equal(await page.evaluate(()=>companionHistory.length),0);
 await page.setViewportSize({width:390,height:844});
 await page.locator('#companion-toggle').click();
 const rect=await page.locator('#companion-panel').boundingBox();
 assert.ok(rect.height<=844*.61 && rect.x>=0 && rect.x+rect.width<=390);
 await page.waitForTimeout(1000);
 await page.screenshot({path:path.join(output,'mobile-preview.png')});
 await page.unroute('http://127.0.0.1:8765/api/chat');
 await page.route('http://127.0.0.1:8765/api/chat',r=>r.abort());
 await page.locator('#companion-input').fill('测试失败'); await page.locator('#companion-input').press('Enter');
 await page.waitForFunction(()=>!companionBusy && !companionRetry.hidden);
 assert.equal(await page.evaluate(()=>companionHistory.length),0);
 await page.unroute('http://127.0.0.1:8765/api/chat');
 await page.route('http://127.0.0.1:8765/api/chat',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({reply:'虚构重试成功'})}));
 await page.locator('#companion-retry').click();
 await page.waitForFunction(()=>!companionBusy && companionHistory.length===2);
 assert.deepEqual(errors,[]); assert.deepEqual(external,[]);
 console.log(JSON.stringify({desktop:true,mobile:true,send:true,duplicateGuard:true,errorRetry:true,gameStart:true,chargeJumpLanding:true,flip:true,cameraNonnegative:true,deathRestart:true,noPageErrors:true,noThirdPartyRequests:true}));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
